Resources: 
  DataTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: '${self:custom.dynamodb.tableName}'
      KeySchema: 
        - AttributeName: 'partitionKey'
          KeyType: 'HASH'
        - AttributeName: 'sortKey'
          KeyType: 'RANGE'
      AttributeDefinitions: 
        - AttributeName: partitionKey
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
        - AttributeName: versionPartitionKey
          AttributeType: S
        - AttributeName: versionSortKey
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: version-index
          KeySchema:
            - AttributeName: versionPartitionKey
              KeyType: HASH
            - AttributeName: versionSortKey
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
